// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uvftkisrphtxwxkmktwk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV2ZnRraXNycGh0eHd4a21rdHdrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzMjcxNzUsImV4cCI6MjA2NTkwMzE3NX0.OCVFQ2zQGjS5nzydp2H1AmbeS6qQfJi6bcnut1f4oxM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);